/*
 * FileOpener.java Copyright (C) 2025 Daniel H. Huson
 *
 *  (Some files contain contributions from other authors, who are then mentioned separately.)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package phylosketch.io;

import javafx.application.Platform;
import jloda.fx.util.RecentFilesManager;
import jloda.fx.window.MainWindowManager;
import jloda.fx.window.NotificationManager;
import jloda.util.FileUtils;
import phylosketch.main.NewWindow;
import phylosketch.main.Version;
import phylosketch.view.DrawView;
import phylosketch.view.ZoomToFit;
import phylosketch.window.MainWindow;
import phylosketch.window.NameUtils;

import java.io.File;
import java.io.IOException;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * opens a file
 * Daniel Huson, 9.2024
 */
public class FileOpener implements Consumer<String> {

	@Override
	public void accept(String fileName) {
		var window = (MainWindow) MainWindowManager.getInstance().getLastFocusedMainWindow();
		if (window == null || !window.isEmpty()) {
			window = NewWindow.apply();
		}
		var fWindow = window;
		Platform.runLater(() -> accept(fileName, fWindow));
	}

	public void accept(String fileName, MainWindow window) {
		var firstLine = Objects.requireNonNull(FileUtils.getFirstLineFromFile(new File(fileName))).trim().toLowerCase();
		var document = window.getDocument();
		try {
			var untitled = FileUtils.getFileNameWithoutPath(fileName).toLowerCase().contains("untitled");
			if(firstLine.startsWith("graph")) {
				PhyloSketchIO.open(fileName, window.getDrawView(), window.getPresenter().getCapturePane().getImageView());
				var name = window.getDrawView().getGraph().getName();
				if (name != null && !name.isBlank()) {
					document.setName(name);
					document.setNameAuto(name.toLowerCase().startsWith("untitled") || name.startsWith(NameUtils.deriveDocumentName(window)));
				} else if (untitled) {
					document.setName(NameUtils.deriveDocumentName(window));
					document.setNameAuto(true);
				} else
					document.setName(FileUtils.getFileNameWithoutPathOrSuffix(fileName));
				document.setFileName(fileName);
				window.getDrawView().setMode(DrawView.Mode.View);
				ZoomToFit.apply(window);
			}
			else if (firstLine.startsWith("#nexus")) {
				if (PhyloSketch1Import.looksLikePhyloSketch1(firstLine)) {
					PhyloSketch1Import.apply(fileName, window.getDrawView());
					document.setName(FileUtils.getFileNameWithoutPathOrSuffix(fileName));
					document.setFileName(FileUtils.replaceFileSuffix(fileName, Version.SUFFIX));
					document.setNameAuto(untitled);
					if (fileName.endsWith(Version.SUFFIX))
						PhyloSketchIO.save(new File(document.getFileName()), window.getDrawView(), window.getPresenter().getCapturePane().getImageView());
					else document.setDirty(true);
				} else
					NotificationManager.showWarning("Invalid nexus: Can only open nexus files generated by PhyloSketch1");
			}
			else if (firstLine.startsWith("<nex:nexml") || firstLine.startsWith("<?xml version="))
				NotificationManager.showWarning("NEXML: not implemented");
			else if (firstLine.startsWith("(") || firstLine.contains(")")) {
				ImportNewick.apply(window, fileName);
				document.setName(FileUtils.getFileNameWithoutPathOrSuffix(fileName));
				document.setFileName(FileUtils.replaceFileSuffix(fileName, Version.SUFFIX));
				document.setNameAuto(untitled);
				if (fileName.endsWith(Version.SUFFIX))
					PhyloSketchIO.save(new File(document.getFileName()), window.getDrawView(), window.getPresenter().getCapturePane().getImageView());
				else document.setDirty(true);
				window.getDrawView().setMode(DrawView.Mode.View);
			} else {
				if (untitled) {
					document.setName(NameUtils.deriveDocumentName(window));
					document.setNameAuto(true);
				} else {
					document.setName(FileUtils.getFileNameWithoutPathOrSuffix(fileName));
					document.setNameAuto(false);
				}
			}
			RecentFilesManager.getInstance().insertRecentFile(fileName);
		} catch (IOException e) {
			NotificationManager.showError("Open file failed: " + e.getMessage());
		}
	}
}